name = "livenotes"
compatibility_date = "2026-04-29"
compatibility_flags = ["nodejs_compat"]

[env.staging]
name = "livenotes-staging"
compatibility_date = "2026-04-27"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./dist/LiveNotes_Angular/browser"
not_found_handling = "single-page-application"

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1
